CREATE OR REPLACE TASK ETL.OBH_MIRAH_COVERAGE_ETL_TO_COMPACT_LOAD
WAREHOUSE = ECT_PRD_OBH_DP_LOAD_WH
SCHEDULE = 'USING CRON 0 11 * * TUE UTC'
COMMENT = 'LOAD COVERAGE data from ETL to COMPACT table'
as CALL ETL.MIRAH_COVERAGE();