CREATE OR REPLACE VIEW ECT_PRD_OBH_DP_DB.MBC.MIRAH_COVERAGE_VIEW(
ID COMMENT 'MEMBER IDENTIFICATION NUMBER.',
PATIENTID COMMENT 'PATIENT IDENTIFICATION NUMBER.'
) as SELECT
	ID,
	PATIENTID FROM "ECT_PRD_OBH_DP_DB"."FOUNDATION"."MIRAH_COVERAGE";